databases:
  - name: chiritsumo-db
    databaseName: chiritsumo_db
    user: chiritsumo-db
    region: singapore

services:
  - type: web
    name: chiritsumo-db
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chiritsumo-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
